config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :dashboard, path: "~" do
    root "home#index"

    resources :glossaries do
      scope module: "glossaries" do
        resources :vocabularies, only: %i[index create destroy] do
          collection do
            post "import"
          end
        end
      end
    end

    resources :meta_prompts do
      scope module: "meta_prompts" do
        resources :units, only: %i[index create update destroy]
      end
    end

    resources :prompt_tasks do
      collection do
        post "batch", action: "batch_create"
      end

      member do
        patch "submit"
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  get "/privacy", to: "home#privacy"
  get "/terms", to: "home#terms"

  get "401", to: "errors#unauthorized", as: :unauthorized
  get "403", to: "errors#forbidden", as: :forbidden
  get "404", to: "errors#not_found", as: :not_found

  devise_scope :user do
    namespace :users, as: "user" do
      resource :registration,
               only: %i[new create],
               path: "",
               path_names: { new: "sign_up" }

      resource :invitation, only: %i[] do
        get :edit, path: "accept", as: :accept
        get :destroy, path: "remove", as: :remove
      end

      match "sign_out" => "sessions#destroy", via: %i[get delete], as: :sign_out
    end
  end

  devise_for :users, skip: %i[registrations invitations], controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "sign_up", to: redirect("/users/sign_up")
  get "sign_in", to: redirect("/users/sign_in")

  namespace :account, module: "accounts" do
    resource :password, only: %i[show update]
    resource :profile, only: %i[show update]
  end
end

app/models/meta_prompt.rb
# frozen_string_literal: true

class MetaPrompt < ApplicationRecord
  belongs_to :user

  has_many :units, class_name: "MetaPromptUnit", dependent: :delete_all
  # accepts_nested_attributes_for :units

  has_many :prompt_tasks, dependent: :nullify

  validates :name,
            presence: true,
            allow_blank: false

  validates :prompt,
            presence: true,
            allow_blank: false

  validates :sd_model_name,
            presence: true,
            inclusion: {
              in: Constants::SUPPORTED_SD_MODEL_NAMES,
              message: "%{value} isn't supported."
            },
            allow_blank: false

  validates :sampler_name,
            presence: true,
            inclusion: {
              in: Constants::SUPPORTED_SAMPLER_NAMES,
              message: "%{value} isn't supported."
            },
            allow_blank: false

  validates :width,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: Constants::WIDTH_RANGE.begin,
              less_than_or_equal_to: Constants::WIDTH_RANGE.end
            },
            allow_blank: false

  validates :height,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: Constants::HEIGHT_RANGE.begin,
              less_than_or_equal_to: Constants::HEIGHT_RANGE.end
            },
            allow_blank: false

  validates :fixed_seed,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: Constants::RANDOM_SEED_RANGE.begin,
              less_than_or_equal_to: Constants::RANDOM_SEED_RANGE.end
            },
            allow_blank: false,
            allow_nil: true

  validates :min_steps,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: Constants::STEP_RANGE.begin,
              less_than_or_equal_to: Constants::STEP_RANGE.end,
            },
            allow_blank: false

  validates :max_steps,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: Constants::STEP_RANGE.begin,
              less_than_or_equal_to: Constants::STEP_RANGE.end
            },
            allow_blank: false
  validate do |record|
    if record.max_steps < record.min_steps
      record.errors.add :max_steps, :greater_than_or_equal_to, record.min_steps
    end
  end

  validates :min_cfg_scale,
            presence: true,
            numericality: {
              only_integer: false,
              greater_than_or_equal_to: Constants::CFG_SCALE_RANGE.begin,
              less_than_or_equal_to: Constants::CFG_SCALE_RANGE.end
            },
            allow_blank: false

  validates :max_cfg_scale,
            presence: true,
            numericality: {
              only_integer: false,
              greater_than_or_equal_to: Constants::CFG_SCALE_RANGE.begin,
              less_than_or_equal_to: Constants::CFG_SCALE_RANGE.end
            },
            allow_blank: false
  validate do |record|
    if record.max_cfg_scale < record.min_cfg_scale
      record.errors.add :max_cfg_scale, :greater_than_or_equal_to, record.min_cfg_scale
    end
  end

  validates :min_clip_skip,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: Constants::CLIP_SKIP_RANGE.begin,
              less_than_or_equal_to: Constants::CLIP_SKIP_RANGE.end
            },
            allow_blank: false

  validates :max_clip_skip,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: Constants::CLIP_SKIP_RANGE.begin,
              less_than_or_equal_to: Constants::CLIP_SKIP_RANGE.end
            },
            allow_blank: false
  validate do |record|
    if record.max_clip_skip < record.min_clip_skip
      record.errors.add :max_clip_skip, :greater_than_or_equal_to, record.min_clip_skip
    end
  end

  validates :hires_fix_upscaler_name,
            presence: true,
            inclusion: {
              in: Constants::SUPPORTED_HIRES_UPSCALER_NAMES,
              message: "%{value} isn't supported."
            },
            allow_blank: false,
            if: :hires_fix?

  validates :hires_fix_min_upscale,
            presence: true,
            numericality: {
              only_integer: false,
              greater_than_or_equal_to: Constants::HIRES_FIX_UPSCALE_RANGE.begin,
              less_than_or_equal_to: Constants::HIRES_FIX_UPSCALE_RANGE.end
            },
            allow_blank: false,
            if: :hires_fix?

  validates :hires_fix_max_upscale,
            presence: true,
            numericality: {
              only_integer: false,
              greater_than_or_equal_to: Constants::HIRES_FIX_UPSCALE_RANGE.begin,
              less_than_or_equal_to: Constants::HIRES_FIX_UPSCALE_RANGE.end
            },
            allow_blank: false,
            if: :hires_fix?
  validate do |record|
    next unless record.hires_fix?

    if record.hires_fix_max_upscale < record.hires_fix_min_upscale
      record.errors.add :hires_fix_max_upscale, :greater_than_or_equal_to, record.hires_fix_min_upscale
    end
  end

  validates :hires_fix_min_steps,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: Constants::HIRES_FIX_STEPS_RANGE.begin,
              less_than_or_equal_to: Constants::HIRES_FIX_STEPS_RANGE.end
            },
            allow_blank: false,
            if: :hires_fix?

  validates :hires_fix_max_steps,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: Constants::HIRES_FIX_STEPS_RANGE.begin,
              less_than_or_equal_to: Constants::HIRES_FIX_STEPS_RANGE.end
            },
            allow_blank: false,
            if: :hires_fix?
  validate do |record|
    next unless record.hires_fix?

    if record.hires_fix_max_steps < record.hires_fix_min_steps
      record.errors.add :hires_fix_max_steps, :greater_than_or_equal_to, record.hires_fix_min_steps
    end
  end

  validates :hires_fix_min_denoising,
            presence: true,
            numericality: {
              only_integer: false,
              greater_than_or_equal_to: Constants::HIRES_FIX_DENOISING_RANGE.begin,
              less_than_or_equal_to: Constants::HIRES_FIX_DENOISING_RANGE.end
            },
            allow_blank: false,
            if: :hires_fix?

  validates :hires_fix_max_denoising,
            presence: true,
            numericality: {
              only_integer: false,
              greater_than_or_equal_to: Constants::HIRES_FIX_DENOISING_RANGE.begin,
              less_than_or_equal_to: Constants::HIRES_FIX_DENOISING_RANGE.end
            },
            allow_blank: false,
            if: :hires_fix?
  validate do |record|
    next unless record.hires_fix?

    if record.hires_fix_max_denoising < record.hires_fix_min_denoising
      record.errors.add :hires_fix_max_denoising, :greater_than_or_equal_to, record.hires_fix_min_denoising
    end
  end

  after_initialize do |record|
    next unless record.new_record?

    record.name ||= "Untitled"
    record.sd_model_name ||= Constants::SUPPORTED_SD_MODEL_NAMES.first
    record.sampler_name ||= Constants::SUPPORTED_SAMPLER_NAMES.first
    record.width ||= 512
    record.height ||= 512
    record.min_steps ||= 5
    record.max_steps ||= 25
    record.min_cfg_scale ||= 7
    record.max_cfg_scale ||= 7
    record.min_clip_skip ||= 1
    record.max_clip_skip ||= 2
    record.hires_fix ||= false
    record.hires_fix_upscaler_name ||= Constants::SUPPORTED_HIRES_UPSCALER_NAMES.first
    record.hires_fix_min_upscale ||= 2.0
    record.hires_fix_max_upscale ||= 2.0
    record.hires_fix_min_steps ||= 1
    record.hires_fix_max_steps ||= 1
    record.hires_fix_min_denoising ||= 0.7
    record.hires_fix_max_denoising ||= 0.7
  end

  def build_prompt_task
    round_to = -> (b, v) {
      (b / v).round * v
    }

    prompts = [prompt]
    negative_prompts = [negative_prompt]
    units.includes(glossary: :vocabularies).sort_by(&:order).reverse_each do |elem|
      case elem
      when MetaPromptUnits::Vocabulary
        if elem.negative?
          negative_prompts << elem.text
        else
          prompts << elem.text
        end
      when MetaPromptUnits::Glossary
        elem.glossary.vocabularies.sample(elem.frequency).each do |vocabulary|
          if elem.negative?
            negative_prompts << vocabulary.text
          else
            prompts << vocabulary.text
          end
        end
      else
        next
      end
    end

    # TODO: quote prompts

    prompt_tasks.build(
      prompt: prompts.reject(&:blank?).join(", ").delete("\r").tr("\n", " ").strip,
      negative_prompt: negative_prompts.reject(&:blank?).join(", ").delete("\r").tr("\n", " ").strip,
      sd_model_name: sd_model_name,
      sampler_name: sampler_name,
      width: width,
      height: height,
      seed: fixed_seed.present? ? fixed_seed : rand(Constants::RANDOM_SEED_RANGE),
      steps: rand(min_steps..max_steps),
      cfg_scale: round_to.call(rand(min_cfg_scale..max_cfg_scale), 0.5).truncate(1),
      clip_skip: rand(min_clip_skip..max_clip_skip),
      hires_fix: hires_fix,
      hires_fix_upscaler_name: hires_fix_upscaler_name,
      hires_fix_upscale: round_to.call(rand(hires_fix_min_upscale..hires_fix_max_upscale), 0.5).truncate(2),
      hires_fix_steps: rand(hires_fix_min_steps..hires_fix_max_steps),
      hires_fix_denoising: rand(hires_fix_min_denoising..hires_fix_max_denoising).truncate(2)
    )
  end
end

app/controllers/dashboard/meta_prompts/application_controller.rb
# frozen_string_literal: true

module Dashboard
  module MetaPrompts
    class ApplicationController < Dashboard::ApplicationController
      before_action :set_meta_prompt
      before_action :ensure_owner!

      protected
        def ensure_owner!
          if @meta_prompt.user != current_user
            flash[:alert] = "You have no permission."
            redirect_back fallback_location: dashboard_meta_prompts_url, status: :see_other
          end
        end

        def set_meta_prompt
          @meta_prompt = MetaPrompt.find(params[:meta_prompt_id])
        end
    end
  end
end

app/controllers/dashboard/meta_prompts/units_controller.rb
# frozen_string_literal: true

module Dashboard::MetaPrompts
  class UnitsController < Dashboard::MetaPrompts::ApplicationController
    before_action :set_meta_prompt_unit, only: %i[update destroy]

    def index
      @meta_prompt_units = @meta_prompt.units.includes(:glossary)
    end

    def create
      type =
        case params[:_type]
        when "Vocabulary"
          MetaPromptUnits::Vocabulary
        when "Glossary"
          MetaPromptUnits::Glossary
        else
          redirect_to dashboard_meta_prompt_url(@meta_prompt)
          return
        end
      @meta_prompt_unit = @meta_prompt.units.build(type: type)
      @meta_prompt_unit.assign_attributes meta_prompt_unit_params

      if @meta_prompt_unit.save
        # flash[:notice] = "Prompt unit was successfully created."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      else
        flash[:alert] = "Prompt unit fails to add."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      end
    end

    def update
      if @meta_prompt_unit.update(meta_prompt_unit_params)
        flash[:notice] = "Prompt unit was successfully updated."
        redirect_to dashboard_meta_prompt_url(@meta_prompt), status: :see_other
      else
        flash[:alert] = "Prompt unit fails to update."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      end
    end

    def destroy
      @meta_prompt_unit.destroy!

      redirect_to dashboard_meta_prompt_url(@meta_prompt), status: :see_other
    end

    private
      def set_meta_prompt_unit
        @meta_prompt_unit = @meta_prompt.units.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def meta_prompt_unit_params
        params.require(:meta_prompt_unit).permit(
          :negative,
          :text,
          :glossary_id,
          :frequency
        )
      end
  end
end

app/controllers/dashboard/meta_prompts_controller.rb
# frozen_string_literal: true

module Dashboard
  class MetaPromptsController < Dashboard::ApplicationController
    before_action :set_meta_prompt, only: %i[show edit update destroy]
    before_action :ensure_owner!, except: %i[index new create]

    def index
      @meta_prompts = MetaPrompt.where(user: current_user).page(params[:page]).per(params[:per_page])
    end

    def show
    end

    def new
      template =
        if params[:template_id].present?
          Settings.templates[params[:template_id].to_i].to_h.except(:_comment)
        else
          {}
        end

      @meta_prompt = MetaPrompt.new template
    end

    def edit
    end

    def create
      @meta_prompt = MetaPrompt.new(meta_prompt_params)
      @meta_prompt.user = current_user

      if @meta_prompt.save
        flash[:notice] = "Plan was successfully created."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @meta_prompt.update(meta_prompt_params)
        flash[:notice] = "Plan was successfully updated."
        redirect_to dashboard_meta_prompt_url(@meta_prompt), status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @meta_prompt.destroy!

      flash[:notice] = "Plan was successfully destroyed."
      redirect_to dashboard_meta_prompts_url, status: :see_other
    end

    private
      def ensure_owner!
        if @meta_prompt.user != current_user
          flash[:alert] = "You have no permission."
          redirect_back fallback_location: dashboard_meta_prompts_url, status: :see_other
        end
      end

      def set_meta_prompt
        @meta_prompt = MetaPrompt.find(params[:id])
      end

      def meta_prompt_params
        params.require(:meta_prompt).permit(
          :name,
          :prompt,
          :negative_prompt,
          :sd_model_name,
          :sampler_name,
          :width,
          :height,
          :fixed_seed,
          :min_steps,
          :max_steps,
          :min_cfg_scale,
          :max_cfg_scale,
          :hires_fix,
          :hires_fix_upscaler_name,
          :hires_fix_min_upscale,
          :hires_fix_max_upscale,
          :hires_fix_min_steps,
          :hires_fix_max_steps,
          :hires_fix_min_denoising,
          :hires_fix_max_denoising
        )
      end
  end
end

app/views/dashboard/meta_prompts/units/_inline_glossary_unit_form.html.erb
<%= form_with(model: unit, scope: :meta_prompt_unit, url: dashboard_meta_prompt_units_path(meta_prompt), local: true, class: "row row-cols-lg-auto g-3 align-items-center mb-3") do |f| %>
  <%= hidden_field_tag "_inline", true %>
  <%= hidden_field_tag "_type", "Glossary" %>

  <div class="col-12">
    <%= f.collection_select :glossary_id, Glossary.where(user: current_user), :id, :name, { include_blank: false }, class: "form-select", class_for_error: "is-invalid" %>
    <%= f.error_message :glossary_id, class: "invalid-feedback" %>
  </div>

  <div class="col-12">
    <%= f.label :frequency %>
  </div>
  <div class="col-12">
    <%= f.number_field :frequency, required: "required", class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :frequency, class: "invalid-feedback" %>
  </div>

  <div class="col-12">
    <div class="form-check">
      <%= f.check_box :negative, class: "form-check-input" %>
      <%= f.label :negative, class: "form-check-label" %>
    </div>
  </div>

  <div class="col-12">
    <%= f.submit "Add", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/dashboard/meta_prompts/units/_inline_vocabulary_unit_form.html.erb
<%= form_with(model: unit, scope: :meta_prompt_unit, url: dashboard_meta_prompt_units_path(meta_prompt), local: true, class: "row row-cols-lg-auto g-3 align-items-center mb-3") do |f| %>
  <%= hidden_field_tag "_inline", true %>
  <%= hidden_field_tag "_type", "Vocabulary" %>

  <div class="col-12">
    <%= f.text_field :text, required: "required", class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :text, class: "invalid-feedback" %>
  </div>

  <div class="col-12">
    <div class="form-check">
      <%= f.check_box :negative, class: "form-check-input" %>
      <%= f.label :negative, class: "form-check-label" %>
    </div>
  </div>

  <div class="col-12">
    <%= f.submit "Add", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/dashboard/meta_prompts/units/index.html.erb
<div class="row align-items-center justify-content-between g-3 mb-3">
  <div class="col-12 col-md-auto">
    <h2 class="mb-0"><%= @meta_prompt.name %></h2>
  </div>
  <div class="col-12 col-md-auto d-flex">
    <%= button_to dashboard_prompt_tasks_path(meta_prompt_id: @meta_prompt.id), class: "btn btn-primary px-3 px-sm-5 me-2" do %>
      <span class="d-none d-sm-inline">
        Try ONE
      </span>
    <% end %>
    <%= button_to batch_dashboard_prompt_tasks_path(meta_prompt_id: @meta_prompt.id, batch_size: 10, auto_submit: true), class: "btn btn-primary px-3 px-sm-5 me-2" do %>
      <span class="d-none d-sm-inline">
        Make TEN
      </span>
    <% end %>
    <%= link_to edit_dashboard_meta_prompt_path(@meta_prompt), class: "btn btn-outline-primary px-3 px-sm-5 me-2" do %>
      <span class="d-none d-sm-inline">
        Edit
      </span>
    <% end %>
    <div>
      <button class="btn px-3 btn-outline-secondary" type="button" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="true" data-bs-reference="parent">
        <i class="bi bi-three-dots"></i>
      </button>
      <ul class="dropdown-menu dropdown-menu-end" data-popper-placement="bottom-end">
        <li>
          <%= button_to "Delete", dashboard_meta_prompt_path(@meta_prompt), method: :delete, class: "dropdown-item text-danger" %>
        </li>
      </ul>
    </div>
  </div>
</div>

<dl class="row mb-3">
  <dt class="col-sm-3">
    SD model
  </dt>
  <dd class="col-sm-9">
    <%= @meta_prompt.sd_model_name %>
  </dd>

  <dt class="col-sm-3">
    Sampler
  </dt>
  <dd class="col-sm-9">
    <%= @meta_prompt.sampler_name %>
  </dd>

  <dt class="col-sm-3">
    Width x Height
  </dt>
  <dd class="col-sm-9">
    <%= @meta_prompt.width %> x <%= @meta_prompt.height %>
  </dd>

  <dt class="col-sm-3">
    Steps
  </dt>
  <dd class="col-sm-9">
    <%- if @meta_prompt.min_steps == @meta_prompt.max_steps %>
      <%= @meta_prompt.min_steps %>
    <% else %>
      <%= @meta_prompt.min_steps %> ~ <%= @meta_prompt.max_steps %>
    <% end -%>
  </dd>

  <dt class="col-sm-3">
    CFG scale
  </dt>
  <dd class="col-sm-9">
    <%- if @meta_prompt.min_cfg_scale == @meta_prompt.max_cfg_scale %>
      <%= @meta_prompt.min_cfg_scale %>
    <% else %>
      <%= @meta_prompt.min_cfg_scale %> ~ <%= @meta_prompt.max_cfg_scale %>
    <% end -%>
  </dd>

  <dt class="col-sm-3">
    Clip skip
  </dt>
  <dd class="col-sm-9">
    <%- if @meta_prompt.min_clip_skip == @meta_prompt.max_clip_skip %>
      <%= @meta_prompt.min_clip_skip %>
    <% else %>
      <%= @meta_prompt.min_clip_skip %> ~ <%= @meta_prompt.max_clip_skip %>
    <% end -%>
  </dd>

  <%- if @meta_prompt.hires_fix? %>
    <dt class="col-sm-3">
      Hires. upscaler
    </dt>
    <dd class="col-sm-9">
      <%= @meta_prompt.hires_fix_upscaler_name %>
    </dd>

    <dt class="col-sm-3">
      Hires. upscale
    </dt>
    <dd class="col-sm-9">
      <%= @meta_prompt.hires_fix_upscale %>
    </dd>

    <dt class="col-sm-3">
      Hires. steps
    </dt>
    <dd class="col-sm-9">
      <%- if @meta_prompt.hires_fix_min_steps == @meta_prompt.hires_fix_max_steps %>
        <%= @meta_prompt.hires_fix_min_steps %>
      <% else %>
        <%= @meta_prompt.hires_fix_min_steps %> ~ <%= @meta_prompt.hires_fix_max_steps %>
      <% end -%>
    </dd>

    <dt class="col-sm-3">
      Hires. denoising
    </dt>
    <dd class="col-sm-9">
      <%- if @meta_prompt.hires_fix_min_denoising == @meta_prompt.hires_fix_max_denoising %>
        <%= @meta_prompt.hires_fix_min_denoising %>
      <% else %>
        <%= @meta_prompt.hires_fix_min_denoising %> ~ <%= @meta_prompt.hires_fix_max_denoising %>
      <% end -%>
    </dd>
  <% end -%>
</dl>

<div>Add vocabulary</div>
<%= render "inline_vocabulary_unit_form", meta_prompt: @meta_prompt, unit: MetaPromptUnits::Vocabulary.new %>
<div>Add glossary</div>
<%= render "inline_glossary_unit_form", meta_prompt: @meta_prompt, unit: MetaPromptUnits::Glossary.new %>

<table class="table align-middle">
  <thead>
  <tr>
    <th scope="col"></th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @meta_prompt_units.each do |meta_prompt_unit| %>
    <tr>
      <th scope="row">
        <%= meta_prompt_unit.negative? ? "-" : "+" %>
      </th>
      <td>
        <%- case meta_prompt_unit %>
        <%- when MetaPromptUnits::Vocabulary %>
          V: <%= meta_prompt_unit.text %>
        <%- when MetaPromptUnits::Glossary %>
          G: <%= meta_prompt_unit.glossary.name %> (freq. <%= meta_prompt_unit.frequency %>)
        <%- else %>
          INVALID
        <% end -%>
      </td>
      <td>
        <%= button_to "Delete", dashboard_meta_prompt_unit_path(@meta_prompt, meta_prompt_unit), method: :delete, class: "btn btn-outline-danger btn-sm" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>