config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :dashboard, path: "~" do
    root "home#index"

    resources :glossaries do
      scope module: "glossaries" do
        resources :vocabularies, only: %i[index create destroy] do
          collection do
            post "import"
          end
        end
      end
    end

    resources :meta_prompts do
      scope module: "meta_prompts" do
        resources :units, only: %i[index create update destroy]
      end
    end

    resources :prompt_tasks do
      collection do
        post "batch", action: "batch_create"
      end

      member do
        patch "submit"
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  get "/privacy", to: "home#privacy"
  get "/terms", to: "home#terms"

  get "401", to: "errors#unauthorized", as: :unauthorized
  get "403", to: "errors#forbidden", as: :forbidden
  get "404", to: "errors#not_found", as: :not_found

  devise_scope :user do
    namespace :users, as: "user" do
      resource :registration,
               only: %i[new create],
               path: "",
               path_names: { new: "sign_up" }

      resource :invitation, only: %i[] do
        get :edit, path: "accept", as: :accept
        get :destroy, path: "remove", as: :remove
      end

      match "sign_out" => "sessions#destroy", via: %i[get delete], as: :sign_out
    end
  end

  devise_for :users, skip: %i[registrations invitations], controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "sign_up", to: redirect("/users/sign_up")
  get "sign_in", to: redirect("/users/sign_in")

  namespace :account, module: "accounts" do
    resource :password, only: %i[show update]
    resource :profile, only: %i[show update]
  end
end

app/controllers/dashboard/application_controller.rb
# frozen_string_literal: true

module Dashboard
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
    before_action :set_page_layout_data, if: -> { request.format.html? }

    protected
      def set_page_layout_data
        prepare_meta_tags title: t("accounts.#{controller_name}.show.title")
        @_sidebar_name = "dashboard"
      end
  end
end

app/controllers/dashboard/glossaries/application_controller.rb
# frozen_string_literal: true

module Dashboard
  module Glossaries
    class ApplicationController < Dashboard::ApplicationController
      before_action :set_glossary
      before_action :ensure_owner!

      protected
        def ensure_owner!
          if @glossary.user != current_user
            flash[:alert] = "You have no permission."
            redirect_back fallback_location: dashboard_glossaries_url, status: :see_other
          end
        end

        def set_glossary
          @glossary = Glossary.find(params[:glossary_id])
        end
    end
  end
end

app/controllers/dashboard/glossaries/vocabularies_controller.rb
# frozen_string_literal: true

module Dashboard::Glossaries
  class VocabulariesController < Dashboard::Glossaries::ApplicationController
    before_action :set_vocabulary, only: %i[destroy]

    def index
      @vocabularies = @glossary.vocabularies
    end

    def create
      @vocabulary = @glossary.vocabularies.build(vocabulary_params)

      if @vocabulary.save
        # flash[:notice] = "Vocabulary was successfully created."
        redirect_to dashboard_glossary_vocabularies_url(@glossary)
      else
        flash[:alert] = "Vocabulary fails to add."
        redirect_to dashboard_glossary_vocabularies_url(@glossary)
      end
    end

    def import
      texts = params[:comma_separated_text].to_s.split(",").filter_map(&:strip)
      # This skip uniqueness check
      # @glossary.vocabularies.insert_all(
      #   texts.map { |text| { text: text } }
      # )
      texts.each do |text|
        @glossary.vocabularies.create text: text
      end
      redirect_to dashboard_glossary_vocabularies_url(@glossary)
    end

    def destroy
      @vocabulary.destroy!

      redirect_to dashboard_glossary_vocabularies_url(@glossary), status: :see_other
    end

    private
      def set_vocabulary
        @vocabulary = @glossary.vocabularies.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def vocabulary_params
        params.require(:vocabulary).permit(:text)
      end
  end
end

app/controllers/dashboard/glossaries_controller.rb
# frozen_string_literal: true

module Dashboard
  class GlossariesController < Dashboard::ApplicationController
    before_action :set_glossary, only: %i[show edit update destroy]
    before_action :ensure_owner!, except: %i[index new create]

    def index
      @glossaries = Glossary.where(user: current_user).page(params[:page]).per(params[:per_page])
    end

    def show
      redirect_to dashboard_glossary_vocabularies_url(@glossary), status: :see_other
    end

    def new
      @glossary = Glossary.new
    end

    def edit
    end

    def create
      @glossary = Glossary.new(glossary_params)
      @glossary.user = current_user

      if @glossary.save
        flash[:notice] = "Glossary was successfully created."
        redirect_to dashboard_glossary_url(@glossary)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @glossary.update(glossary_params)
        flash[:notice] = "Glossary was successfully updated."
        redirect_to dashboard_glossary_url(@glossary), status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @glossary.destroy!

      flash[:notice] = "Glossary was successfully destroyed."
      redirect_to dashboard_glossaries_url, status: :see_other
    end

    private
      def ensure_owner!
        if @glossary.user != current_user
          flash[:alert] = "You have no permission."
          redirect_back fallback_location: dashboard_glossaries_url, status: :see_other
        end
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_glossary
        @glossary = Glossary.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def glossary_params
        params.require(:glossary).permit(:name, :description)
      end
  end
end

app/controllers/dashboard/home_controller.rb
# frozen_string_literal: true

module Dashboard
  class HomeController < Dashboard::ApplicationController
    def index
    end
  end
end

app/controllers/dashboard/meta_prompts/application_controller.rb
# frozen_string_literal: true

module Dashboard
  module MetaPrompts
    class ApplicationController < Dashboard::ApplicationController
      before_action :set_meta_prompt
      before_action :ensure_owner!

      protected
        def ensure_owner!
          if @meta_prompt.user != current_user
            flash[:alert] = "You have no permission."
            redirect_back fallback_location: dashboard_meta_prompts_url, status: :see_other
          end
        end

        def set_meta_prompt
          @meta_prompt = MetaPrompt.find(params[:meta_prompt_id])
        end
    end
  end
end

app/controllers/dashboard/meta_prompts/units_controller.rb
# frozen_string_literal: true

module Dashboard::MetaPrompts
  class UnitsController < Dashboard::MetaPrompts::ApplicationController
    before_action :set_meta_prompt_unit, only: %i[update destroy]

    def index
      @meta_prompt_units = @meta_prompt.units.includes(:glossary)
    end

    def create
      type =
        case params[:_type]
        when "Vocabulary"
          MetaPromptUnits::Vocabulary
        when "Glossary"
          MetaPromptUnits::Glossary
        else
          redirect_to dashboard_meta_prompt_url(@meta_prompt)
          return
        end
      @meta_prompt_unit = @meta_prompt.units.build(type: type)
      @meta_prompt_unit.assign_attributes meta_prompt_unit_params

      if @meta_prompt_unit.save
        # flash[:notice] = "Prompt unit was successfully created."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      else
        flash[:alert] = "Prompt unit fails to add."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      end
    end

    def update
      if @meta_prompt_unit.update(meta_prompt_unit_params)
        flash[:notice] = "Prompt unit was successfully updated."
        redirect_to dashboard_meta_prompt_url(@meta_prompt), status: :see_other
      else
        flash[:alert] = "Prompt unit fails to update."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      end
    end

    def destroy
      @meta_prompt_unit.destroy!

      redirect_to dashboard_meta_prompt_url(@meta_prompt), status: :see_other
    end

    private
      def set_meta_prompt_unit
        @meta_prompt_unit = @meta_prompt.units.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def meta_prompt_unit_params
        params.require(:meta_prompt_unit).permit(
          :negative,
          :text,
          :glossary_id,
          :frequency
        )
      end
  end
end

app/controllers/dashboard/meta_prompts_controller.rb
# frozen_string_literal: true

module Dashboard
  class MetaPromptsController < Dashboard::ApplicationController
    before_action :set_meta_prompt, only: %i[show edit update destroy]
    before_action :ensure_owner!, except: %i[index new create]

    def index
      @meta_prompts = MetaPrompt.where(user: current_user).page(params[:page]).per(params[:per_page])
    end

    def show
    end

    def new
      template =
        if params[:template_id].present?
          Settings.templates[params[:template_id].to_i].to_h.except(:_comment)
        else
          {}
        end

      @meta_prompt = MetaPrompt.new template
    end

    def edit
    end

    def create
      @meta_prompt = MetaPrompt.new(meta_prompt_params)
      @meta_prompt.user = current_user

      if @meta_prompt.save
        flash[:notice] = "Plan was successfully created."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @meta_prompt.update(meta_prompt_params)
        flash[:notice] = "Plan was successfully updated."
        redirect_to dashboard_meta_prompt_url(@meta_prompt), status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @meta_prompt.destroy!

      flash[:notice] = "Plan was successfully destroyed."
      redirect_to dashboard_meta_prompts_url, status: :see_other
    end

    private
      def ensure_owner!
        if @meta_prompt.user != current_user
          flash[:alert] = "You have no permission."
          redirect_back fallback_location: dashboard_meta_prompts_url, status: :see_other
        end
      end

      def set_meta_prompt
        @meta_prompt = MetaPrompt.find(params[:id])
      end

      def meta_prompt_params
        params.require(:meta_prompt).permit(
          :name,
          :prompt,
          :negative_prompt,
          :sd_model_name,
          :sampler_name,
          :width,
          :height,
          :fixed_seed,
          :min_steps,
          :max_steps,
          :min_cfg_scale,
          :max_cfg_scale,
          :hires_fix,
          :hires_fix_upscaler_name,
          :hires_fix_min_upscale,
          :hires_fix_max_upscale,
          :hires_fix_min_steps,
          :hires_fix_max_steps,
          :hires_fix_min_denoising,
          :hires_fix_max_denoising
        )
      end
  end
end

app/controllers/dashboard/prompt_tasks_controller.rb
# frozen_string_literal: true

module Dashboard
  class PromptTasksController < Dashboard::ApplicationController
    before_action :set_prompt_task, except: %i[index new create batch_create]
    before_action :ensure_owner!, except: %i[index new create batch_create]
    before_action :frozen_after_submitted!, except: %i[index new create batch_create show]

    def index
      @prompt_tasks = PromptTask.where(user: current_user).order(id: :desc).page(params[:page]).per(params[:per_page] || 50)
    end

    def batch_create
      meta_prompt =
        if params[:meta_prompt_id].present?
          MetaPrompt.where(user: current_user).where(id: params[:meta_prompt_id]).first
        end
      unless meta_prompt
        flash[:notice] = "Meta prompt not found."
        redirect_back_or_to dashboard_prompt_tasks_url
        return
      end

      created_prompt_tasks = []
      batch_size = params[:batch_size].to_i || 4
      batch_size.times do
        prompt_task = meta_prompt.build_prompt_task
        prompt_task.user = current_user

        if prompt_task.save
          created_prompt_tasks << prompt_task
        end
      end

      if params[:auto_submit]
        created_prompt_tasks.each(&:submit!)
      end

      flash[:notice] = "Batch created #{created_prompt_tasks.size} tasks"
      redirect_to dashboard_prompt_tasks_url
    end

    def new
      meta_prompt =
        if params[:meta_prompt_id].present?
          MetaPrompt.where(user: current_user).where(id: params[:meta_prompt_id]).first
        end
      @prompt_task = meta_prompt ? meta_prompt.build_prompt_task : PromptTask.new
    end

    def create
      meta_prompt =
        if params[:meta_prompt_id].present?
          MetaPrompt.where(user: current_user).where(id: params[:meta_prompt_id]).first
        end
      @prompt_task = meta_prompt ? meta_prompt.build_prompt_task : PromptTask.new
      @prompt_task.user = current_user

      if @prompt_task.save
        flash[:notice] = "Task was successfully created."
        redirect_to dashboard_prompt_task_url(@prompt_task)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def show
    end

    def edit
    end

    def update
      if @prompt_task.update(prompt_task_params)
        flash[:notice] = "Task was successfully updated."
        redirect_to dashboard_prompt_task_url(@prompt_task), status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @prompt_task.destroy!

      flash[:notice] = "Task was successfully destroyed."
      redirect_to dashboard_prompt_tasks_url, status: :see_other
    end

    def submit
      @prompt_task.submit!
      redirect_to dashboard_prompt_task_url(@prompt_task), status: :see_other
    end

    private
      def ensure_owner!
        if @prompt_task.user != current_user
          flash[:alert] = "You have no permission."
          redirect_back fallback_location: dashboard_prompt_tasks_url, status: :see_other
        end
      end

      def frozen_after_submitted!
        unless @prompt_task.pending?
          flash[:alert] = "The task has frozen."
          redirect_back fallback_location: dashboard_prompt_task_url(@prompt_task), status: :see_other
        end
      end

      def set_prompt_task
        @prompt_task = PromptTask.find(params[:id])
      end

      def prompt_task_params
        params.require(:prompt_task).permit(
          :prompt,
          :negative_prompt,
          :sd_model_name,
          :sampler_name,
          :width,
          :height,
          :seed,
          :steps,
          :cfg_scale,
          :hires_fix,
          :hires_fix_upscaler_name,
          :hires_fix_upscale,
          :hires_fix_steps,
          :hires_fix_denoising
        )
      end
  end
end

app/views/dashboard/meta_prompts/edit.html.erb
<div class="row align-items-center justify-content-between g-3 mb-3">
  <div class="col-12 col-md-auto">
    <h2 class="mb-0">Editing meta prompt</h2>
  </div>
</div>

<%= render "form", meta_prompt: @meta_prompt, locals: { back_path: dashboard_meta_prompt_path(@meta_prompt) } %>

app/views/dashboard/meta_prompts/index.html.erb
<div class="row align-items-center justify-content-between g-3 mb-3">
  <div class="col-12 col-md-auto">
    <h2 class="mb-0">Meta prompts</h2>
  </div>
  <div class="col-12 col-md-auto d-flex">
    <%= link_to new_dashboard_meta_prompt_path, class: "btn btn-outline-primary px-3 px-sm-5 me-2" do %>
      <span class="d-none d-sm-inline">
        New
      </span>
    <% end %>
  </div>
</div>

<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @meta_prompts.each do |plan| %>
    <tr>
      <th scope="row">
        <%= plan.id %>
      </th>
      <td>
        <%= plan.name %>
      </td>
      <td>
        <%= link_to "Show", dashboard_meta_prompt_path(plan) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @meta_prompts %>

app/views/dashboard/meta_prompts/new.html.erb
<div class="row align-items-center justify-content-between g-3 mb-3">
  <div class="col-12 col-md-auto">
    <h2 class="mb-0">New meta prompt</h2>
  </div>
</div>

<%= render "form", meta_prompt: @meta_prompt %>

app/views/dashboard/meta_prompts/show.html.erb
<div class="row align-items-center justify-content-between g-3 mb-3">
  <div class="col-12 col-md-auto">
    <h2 class="mb-0"><%= @meta_prompt.name %></h2>
  </div>
  <div class="col-12 col-md-auto d-flex">
    <%= button_to dashboard_prompt_tasks_path(meta_prompt_id: @meta_prompt.id), class: "btn btn-primary px-3 px-sm-5 me-2" do %>
      <span class="d-none d-sm-inline">
        Try ONE
      </span>
    <% end %>
    <%= button_to batch_dashboard_prompt_tasks_path(meta_prompt_id: @meta_prompt.id, batch_size: 5, auto_submit: true), class: "btn btn-primary px-3 px-sm-5 me-2" do %>
      <span class="d-none d-sm-inline">
        Gimme FIVE
      </span>
    <% end %>
    <%= link_to edit_dashboard_meta_prompt_path(@meta_prompt), class: "btn btn-outline-primary px-3 px-sm-5 me-2" do %>
      <span class="d-none d-sm-inline">
        Edit
      </span>
    <% end %>
    <div>
      <button class="btn px-3 btn-outline-secondary" type="button" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="true" data-bs-reference="parent">
        <i class="bi bi-three-dots"></i>
      </button>
      <ul class="dropdown-menu dropdown-menu-end" data-popper-placement="bottom-end">
        <li>
          <%= button_to "Delete", dashboard_meta_prompt_path(@meta_prompt), method: :delete, class: "dropdown-item text-danger" %>
        </li>
      </ul>
    </div>
  </div>
</div>

<dl class="row mb-3">
  <dt class="col-sm-3">
    SD model
  </dt>
  <dd class="col-sm-9">
    <%= @meta_prompt.sd_model_name %>
  </dd>

  <dt class="col-sm-3">
    Prompt
  </dt>
  <dd class="col-sm-9">
    <%= @meta_prompt.prompt %>
  </dd>

  <dt class="col-sm-3">
    Negative prompt
  </dt>
  <dd class="col-sm-9">
    <%= @meta_prompt.negative_prompt %>
  </dd>

  <dt class="col-sm-3">
    Sampler
  </dt>
  <dd class="col-sm-9">
    <%= @meta_prompt.sampler_name %>
  </dd>

  <dt class="col-sm-3">
    Width x Height
  </dt>
  <dd class="col-sm-9">
    <%= @meta_prompt.width %> x <%= @meta_prompt.height %>
  </dd>

  <dt class="col-sm-3">
    Steps
  </dt>
  <dd class="col-sm-9">
    <%- if @meta_prompt.min_steps == @meta_prompt.max_steps %>
      <%= @meta_prompt.min_steps %>
    <% else %>
      <%= @meta_prompt.min_steps %> ~ <%= @meta_prompt.max_steps %>
    <% end -%>
  </dd>

  <dt class="col-sm-3">
    CFG scale
  </dt>
  <dd class="col-sm-9">
    <%- if @meta_prompt.min_cfg_scale == @meta_prompt.max_cfg_scale %>
      <%= @meta_prompt.min_cfg_scale %>
    <% else %>
      <%= @meta_prompt.min_cfg_scale %> ~ <%= @meta_prompt.max_cfg_scale %>
    <% end -%>
  </dd>

  <dt class="col-sm-3">
    Clip skip
  </dt>
  <dd class="col-sm-9">
    <%- if @meta_prompt.min_clip_skip == @meta_prompt.max_clip_skip %>
      <%= @meta_prompt.min_clip_skip %>
    <% else %>
      <%= @meta_prompt.min_clip_skip %> ~ <%= @meta_prompt.max_clip_skip %>
    <% end -%>
  </dd>

  <%- if @meta_prompt.hires_fix? %>
    <dt class="col-sm-3">
      Hires. upscaler
    </dt>
    <dd class="col-sm-9">
      <%= @meta_prompt.hires_fix_upscaler_name %>
    </dd>

    <dt class="col-sm-3">
      Hires. upscale
    </dt>
    <dd class="col-sm-9">
      <%- if @meta_prompt.hires_fix_min_upscale == @meta_prompt.hires_fix_max_upscale %>
        <%= @meta_prompt.hires_fix_min_upscale %>
      <% else %>
        <%= @meta_prompt.hires_fix_min_upscale %> ~ <%= @meta_prompt.hires_fix_max_upscale %>
      <% end -%>
    </dd>

    <dt class="col-sm-3">
      Hires. steps
    </dt>
    <dd class="col-sm-9">
      <%- if @meta_prompt.hires_fix_min_steps == @meta_prompt.hires_fix_max_steps %>
        <%= @meta_prompt.hires_fix_min_steps %>
      <% else %>
        <%= @meta_prompt.hires_fix_min_steps %> ~ <%= @meta_prompt.hires_fix_max_steps %>
      <% end -%>
    </dd>

    <dt class="col-sm-3">
      Hires. denoising
    </dt>
    <dd class="col-sm-9">
      <%- if @meta_prompt.hires_fix_min_denoising == @meta_prompt.hires_fix_max_denoising %>
        <%= @meta_prompt.hires_fix_min_denoising %>
      <% else %>
        <%= @meta_prompt.hires_fix_min_denoising %> ~ <%= @meta_prompt.hires_fix_max_denoising %>
      <% end -%>
    </dd>
  <% end -%>
</dl>

<small>
  You could random pick form glossaries to enhance the prompt.
  <%= link_to "Create a glossary", new_dashboard_glossary_path %>
</small>
<%= render "dashboard/meta_prompts/units/inline_glossary_unit_form", meta_prompt: @meta_prompt, unit: MetaPromptUnits::Glossary.new %>

<table class="table align-middle">
  <thead>
  <tr>
    <th scope="col"></th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @meta_prompt.units.each do |meta_prompt_unit| %>
    <tr>
      <th scope="row">
        <%= meta_prompt_unit.negative? ? "-" : "+" %>
      </th>
      <td>
        <%- case meta_prompt_unit %>
        <%- when MetaPromptUnits::Vocabulary %>
          V: <%= meta_prompt_unit.text %>
        <%- when MetaPromptUnits::Glossary %>
          G: <%= meta_prompt_unit.glossary.name %> (freq. <%= meta_prompt_unit.frequency %>)
        <%- else %>
          INVALID
        <% end -%>
      </td>
      <td>
        <%= button_to "Delete", dashboard_meta_prompt_unit_path(@meta_prompt, meta_prompt_unit), method: :delete, class: "btn btn-outline-danger btn-sm" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>