config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :dashboard, path: "~" do
    root "home#index"

    resources :glossaries do
      scope module: "glossaries" do
        resources :vocabularies, only: %i[index create destroy] do
          collection do
            post "import"
          end
        end
      end
    end

    resources :meta_prompts do
      scope module: "meta_prompts" do
        resources :units, only: %i[index create update destroy]
      end
    end

    resources :prompt_tasks do
      collection do
        post "batch", action: "batch_create"
      end

      member do
        patch "submit"
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  get "/privacy", to: "home#privacy"
  get "/terms", to: "home#terms"

  get "401", to: "errors#unauthorized", as: :unauthorized
  get "403", to: "errors#forbidden", as: :forbidden
  get "404", to: "errors#not_found", as: :not_found

  devise_scope :user do
    namespace :users, as: "user" do
      resource :registration,
               only: %i[new create],
               path: "",
               path_names: { new: "sign_up" }

      resource :invitation, only: %i[] do
        get :edit, path: "accept", as: :accept
        get :destroy, path: "remove", as: :remove
      end

      match "sign_out" => "sessions#destroy", via: %i[get delete], as: :sign_out
    end
  end

  devise_for :users, skip: %i[registrations invitations], controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "sign_up", to: redirect("/users/sign_up")
  get "sign_in", to: redirect("/users/sign_in")

  namespace :account, module: "accounts" do
    resource :password, only: %i[show update]
    resource :profile, only: %i[show update]
  end
end

app/controllers/dashboard/application_controller.rb
# frozen_string_literal: true

module Dashboard
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
    before_action :set_page_layout_data, if: -> { request.format.html? }

    protected
      def set_page_layout_data
        prepare_meta_tags title: t("accounts.#{controller_name}.show.title")
        @_sidebar_name = "dashboard"
      end
  end
end

app/controllers/dashboard/glossaries/application_controller.rb
# frozen_string_literal: true

module Dashboard
  module Glossaries
    class ApplicationController < Dashboard::ApplicationController
      before_action :set_glossary
      before_action :ensure_owner!

      protected
        def ensure_owner!
          if @glossary.user != current_user
            flash[:alert] = "You have no permission."
            redirect_back fallback_location: dashboard_glossaries_url, status: :see_other
          end
        end

        def set_glossary
          @glossary = Glossary.find(params[:glossary_id])
        end
    end
  end
end

app/controllers/dashboard/glossaries/vocabularies_controller.rb
# frozen_string_literal: true

module Dashboard::Glossaries
  class VocabulariesController < Dashboard::Glossaries::ApplicationController
    before_action :set_vocabulary, only: %i[destroy]

    def index
      @vocabularies = @glossary.vocabularies
    end

    def create
      @vocabulary = @glossary.vocabularies.build(vocabulary_params)

      if @vocabulary.save
        # flash[:notice] = "Vocabulary was successfully created."
        redirect_to dashboard_glossary_vocabularies_url(@glossary)
      else
        flash[:alert] = "Vocabulary fails to add."
        redirect_to dashboard_glossary_vocabularies_url(@glossary)
      end
    end

    def import
      texts = params[:comma_separated_text].to_s.split(",").filter_map(&:strip)
      # This skip uniqueness check
      # @glossary.vocabularies.insert_all(
      #   texts.map { |text| { text: text } }
      # )
      texts.each do |text|
        @glossary.vocabularies.create text: text
      end
      redirect_to dashboard_glossary_vocabularies_url(@glossary)
    end

    def destroy
      @vocabulary.destroy!

      redirect_to dashboard_glossary_vocabularies_url(@glossary), status: :see_other
    end

    private
      def set_vocabulary
        @vocabulary = @glossary.vocabularies.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def vocabulary_params
        params.require(:vocabulary).permit(:text)
      end
  end
end

app/controllers/dashboard/glossaries_controller.rb
# frozen_string_literal: true

module Dashboard
  class GlossariesController < Dashboard::ApplicationController
    before_action :set_glossary, only: %i[show edit update destroy]
    before_action :ensure_owner!, except: %i[index new create]

    def index
      @glossaries = Glossary.where(user: current_user).page(params[:page]).per(params[:per_page])
    end

    def show
      redirect_to dashboard_glossary_vocabularies_url(@glossary), status: :see_other
    end

    def new
      @glossary = Glossary.new
    end

    def edit
    end

    def create
      @glossary = Glossary.new(glossary_params)
      @glossary.user = current_user

      if @glossary.save
        flash[:notice] = "Glossary was successfully created."
        redirect_to dashboard_glossary_url(@glossary)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @glossary.update(glossary_params)
        flash[:notice] = "Glossary was successfully updated."
        redirect_to dashboard_glossary_url(@glossary), status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @glossary.destroy!

      flash[:notice] = "Glossary was successfully destroyed."
      redirect_to dashboard_glossaries_url, status: :see_other
    end

    private
      def ensure_owner!
        if @glossary.user != current_user
          flash[:alert] = "You have no permission."
          redirect_back fallback_location: dashboard_glossaries_url, status: :see_other
        end
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_glossary
        @glossary = Glossary.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def glossary_params
        params.require(:glossary).permit(:name, :description)
      end
  end
end

app/controllers/dashboard/home_controller.rb
# frozen_string_literal: true

module Dashboard
  class HomeController < Dashboard::ApplicationController
    def index
    end
  end
end

app/controllers/dashboard/meta_prompts/application_controller.rb
# frozen_string_literal: true

module Dashboard
  module MetaPrompts
    class ApplicationController < Dashboard::ApplicationController
      before_action :set_meta_prompt
      before_action :ensure_owner!

      protected
        def ensure_owner!
          if @meta_prompt.user != current_user
            flash[:alert] = "You have no permission."
            redirect_back fallback_location: dashboard_meta_prompts_url, status: :see_other
          end
        end

        def set_meta_prompt
          @meta_prompt = MetaPrompt.find(params[:meta_prompt_id])
        end
    end
  end
end

app/controllers/dashboard/meta_prompts/units_controller.rb
# frozen_string_literal: true

module Dashboard::MetaPrompts
  class UnitsController < Dashboard::MetaPrompts::ApplicationController
    before_action :set_meta_prompt_unit, only: %i[update destroy]

    def index
      @meta_prompt_units = @meta_prompt.units.includes(:glossary)
    end

    def create
      type =
        case params[:_type]
        when "Vocabulary"
          MetaPromptUnits::Vocabulary
        when "Glossary"
          MetaPromptUnits::Glossary
        else
          redirect_to dashboard_meta_prompt_url(@meta_prompt)
          return
        end
      @meta_prompt_unit = @meta_prompt.units.build(type: type)
      @meta_prompt_unit.assign_attributes meta_prompt_unit_params

      if @meta_prompt_unit.save
        # flash[:notice] = "Prompt unit was successfully created."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      else
        flash[:alert] = "Prompt unit fails to add."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      end
    end

    def update
      if @meta_prompt_unit.update(meta_prompt_unit_params)
        flash[:notice] = "Prompt unit was successfully updated."
        redirect_to dashboard_meta_prompt_url(@meta_prompt), status: :see_other
      else
        flash[:alert] = "Prompt unit fails to update."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      end
    end

    def destroy
      @meta_prompt_unit.destroy!

      redirect_to dashboard_meta_prompt_url(@meta_prompt), status: :see_other
    end

    private
      def set_meta_prompt_unit
        @meta_prompt_unit = @meta_prompt.units.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def meta_prompt_unit_params
        params.require(:meta_prompt_unit).permit(
          :negative,
          :text,
          :glossary_id,
          :frequency
        )
      end
  end
end

app/controllers/dashboard/meta_prompts_controller.rb
# frozen_string_literal: true

module Dashboard
  class MetaPromptsController < Dashboard::ApplicationController
    before_action :set_meta_prompt, only: %i[show edit update destroy]
    before_action :ensure_owner!, except: %i[index new create]

    def index
      @meta_prompts = MetaPrompt.where(user: current_user).page(params[:page]).per(params[:per_page])
    end

    def show
    end

    def new
      template =
        if params[:template_id].present?
          Settings.templates[params[:template_id].to_i].to_h.except(:_comment)
        else
          {}
        end

      @meta_prompt = MetaPrompt.new template
    end

    def edit
    end

    def create
      @meta_prompt = MetaPrompt.new(meta_prompt_params)
      @meta_prompt.user = current_user

      if @meta_prompt.save
        flash[:notice] = "Plan was successfully created."
        redirect_to dashboard_meta_prompt_url(@meta_prompt)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @meta_prompt.update(meta_prompt_params)
        flash[:notice] = "Plan was successfully updated."
        redirect_to dashboard_meta_prompt_url(@meta_prompt), status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @meta_prompt.destroy!

      flash[:notice] = "Plan was successfully destroyed."
      redirect_to dashboard_meta_prompts_url, status: :see_other
    end

    private
      def ensure_owner!
        if @meta_prompt.user != current_user
          flash[:alert] = "You have no permission."
          redirect_back fallback_location: dashboard_meta_prompts_url, status: :see_other
        end
      end

      def set_meta_prompt
        @meta_prompt = MetaPrompt.find(params[:id])
      end

      def meta_prompt_params
        params.require(:meta_prompt).permit(
          :name,
          :prompt,
          :negative_prompt,
          :sd_model_name,
          :sampler_name,
          :width,
          :height,
          :fixed_seed,
          :min_steps,
          :max_steps,
          :min_cfg_scale,
          :max_cfg_scale,
          :hires_fix,
          :hires_fix_upscaler_name,
          :hires_fix_min_upscale,
          :hires_fix_max_upscale,
          :hires_fix_min_steps,
          :hires_fix_max_steps,
          :hires_fix_min_denoising,
          :hires_fix_max_denoising
        )
      end
  end
end

app/controllers/dashboard/prompt_tasks_controller.rb
# frozen_string_literal: true

module Dashboard
  class PromptTasksController < Dashboard::ApplicationController
    before_action :set_prompt_task, except: %i[index new create batch_create]
    before_action :ensure_owner!, except: %i[index new create batch_create]
    before_action :frozen_after_submitted!, except: %i[index new create batch_create show]

    def index
      @prompt_tasks = PromptTask.where(user: current_user).order(id: :desc).page(params[:page]).per(params[:per_page] || 50)
    end

    def batch_create
      meta_prompt =
        if params[:meta_prompt_id].present?
          MetaPrompt.where(user: current_user).where(id: params[:meta_prompt_id]).first
        end
      unless meta_prompt
        flash[:notice] = "Meta prompt not found."
        redirect_back_or_to dashboard_prompt_tasks_url
        return
      end

      created_prompt_tasks = []
      batch_size = params[:batch_size].to_i || 4
      batch_size.times do
        prompt_task = meta_prompt.build_prompt_task
        prompt_task.user = current_user

        if prompt_task.save
          created_prompt_tasks << prompt_task
        end
      end

      if params[:auto_submit]
        created_prompt_tasks.each(&:submit!)
      end

      flash[:notice] = "Batch created #{created_prompt_tasks.size} tasks"
      redirect_to dashboard_prompt_tasks_url
    end

    def new
      meta_prompt =
        if params[:meta_prompt_id].present?
          MetaPrompt.where(user: current_user).where(id: params[:meta_prompt_id]).first
        end
      @prompt_task = meta_prompt ? meta_prompt.build_prompt_task : PromptTask.new
    end

    def create
      meta_prompt =
        if params[:meta_prompt_id].present?
          MetaPrompt.where(user: current_user).where(id: params[:meta_prompt_id]).first
        end
      @prompt_task = meta_prompt ? meta_prompt.build_prompt_task : PromptTask.new
      @prompt_task.user = current_user

      if @prompt_task.save
        flash[:notice] = "Task was successfully created."
        redirect_to dashboard_prompt_task_url(@prompt_task)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def show
    end

    def edit
    end

    def update
      if @prompt_task.update(prompt_task_params)
        flash[:notice] = "Task was successfully updated."
        redirect_to dashboard_prompt_task_url(@prompt_task), status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @prompt_task.destroy!

      flash[:notice] = "Task was successfully destroyed."
      redirect_to dashboard_prompt_tasks_url, status: :see_other
    end

    def submit
      @prompt_task.submit!
      redirect_to dashboard_prompt_task_url(@prompt_task), status: :see_other
    end

    private
      def ensure_owner!
        if @prompt_task.user != current_user
          flash[:alert] = "You have no permission."
          redirect_back fallback_location: dashboard_prompt_tasks_url, status: :see_other
        end
      end

      def frozen_after_submitted!
        unless @prompt_task.pending?
          flash[:alert] = "The task has frozen."
          redirect_back fallback_location: dashboard_prompt_task_url(@prompt_task), status: :see_other
        end
      end

      def set_prompt_task
        @prompt_task = PromptTask.find(params[:id])
      end

      def prompt_task_params
        params.require(:prompt_task).permit(
          :prompt,
          :negative_prompt,
          :sd_model_name,
          :sampler_name,
          :width,
          :height,
          :seed,
          :steps,
          :cfg_scale,
          :hires_fix,
          :hires_fix_upscaler_name,
          :hires_fix_upscale,
          :hires_fix_steps,
          :hires_fix_denoising
        )
      end
  end
end

app/views/dashboard/prompt_tasks/_form.html.erb
<%- back_path ||= dashboard_prompt_tasks_path -%>
<%= form_with(model: [:dashboard, prompt_task], local: true) do |f| %>
  <div class="mb-3">
    <%= f.label :prompt %>
    <%= f.text_area :prompt, required: "required", class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :prompt, class: "invalid-feedback" %>
  </div>

  <div class="mb-3">
    <%= f.label :negative_prompt %>
    <%= f.text_area :negative_prompt, class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :negative_prompt, class: "invalid-feedback" %>
  </div>

  <div class="mb-3">
    <%= f.label :sd_model_name %>
    <%= f.select :sd_model_name, Constants::SUPPORTED_SD_MODEL_NAMES, { include_blank: false }, class: "form-select", class_for_error: "is-invalid" %>
    <%= f.error_message :sd_model_name, class: "invalid-feedback" %>
  </div>

  <div class="mb-3">
    <%= f.label :sampler_name %>
    <%= f.select :sampler_name, Constants::SUPPORTED_SAMPLER_NAMES, { include_blank: false }, class: "form-select", class_for_error: "is-invalid" %>
    <%= f.error_message :sampler_name, class: "invalid-feedback" %>
  </div>

  <div class="row mb-3">
    <div class="col">
      <%= f.label :width %>
      <%= f.number_field :width, step: 1, min: Constants::WIDTH_RANGE.begin, max: Constants::WIDTH_RANGE.end, required: "required", class: "form-control", class_for_error: "is-invalid" %>
      <%= f.error_message :width, class: "invalid-feedback" %>
    </div>
    <div class="col">
      <%= f.label :height %>
      <%= f.number_field :height, step: 1, min: Constants::HEIGHT_RANGE.begin, max: Constants::HEIGHT_RANGE.end, required: "required", class: "form-control", class_for_error: "is-invalid" %>
      <%= f.error_message :height, class: "invalid-feedback" %>
    </div>
  </div>

  <div class="mb-3">
    <%= f.label :steps %>
    <%= f.number_field :steps, step: 1, min: Constants::STEP_RANGE.begin, max: Constants::STEP_RANGE.end, required: "required", class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :steps, class: "invalid-feedback" %>
  </div>

  <div class="mb-3">
    <%= f.label :cfg_scale %>
    <%= f.number_field :cfg_scale, step: 0.1, min: Constants::CFG_SCALE_RANGE.begin, max: Constants::CFG_SCALE_RANGE.end, required: "required", class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :cfg_scale, class: "invalid-feedback" %>
  </div>

  <div class="mb-3">
    <%= f.label :clip_skip %>
    <%= f.number_field :clip_skip, step: 1, min: Constants::CLIP_SKIP_RANGE.begin, max: Constants::CLIP_SKIP_RANGE.end, required: "required", class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :clip_skip, class: "invalid-feedback" %>
  </div>

  <div class="mb-3">
    <div class="form-check">
      <%= f.check_box :hires_fix, class: "form-check-input" %>
      <%= f.label :hires_fix, class: "form-check-label" %>
    </div>
  </div>

  <div class="mb-3">
    <%= f.label :hires_fix_upscaler_name %>
    <%= f.select :hires_fix_upscaler_name, Constants::SUPPORTED_HIRES_UPSCALER_NAMES, { include_blank: false }, class: "form-select", class_for_error: "is-invalid" %>
    <%= f.error_message :hires_fix_upscaler_name, class: "invalid-feedback" %>
  </div>

  <div class="mb-3">
    <%= f.label :hires_fix_upscale %>
    <%= f.number_field :hires_fix_upscale, step: 0.01, min: Constants::HIRES_FIX_UPSCALE_RANGE.begin, max: Constants::HIRES_FIX_UPSCALE_RANGE.end, class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :hires_fix_upscale, class: "invalid-feedback" %>
  </div>

  <div class="mb-3">
    <%= f.label :hires_fix_steps %>
    <%= f.number_field :hires_fix_steps, step: 1, min: Constants::HIRES_FIX_STEPS_RANGE.begin, max: Constants::HIRES_FIX_STEPS_RANGE.end, class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :hires_fix_steps, class: "invalid-feedback" %>
  </div>

  <div class="mb-3">
    <%= f.label :hires_fix_denoising %>
    <%= f.number_field :hires_fix_denoising, step: 0.01, min: Constants::HIRES_FIX_DENOISING_RANGE.begin, max: Constants::HIRES_FIX_DENOISING_RANGE.end, class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :hires_fix_denoising, class: "invalid-feedback" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
  <%= link_to "Discard & back", back_path, class: "btn btn-link" %>
<% end %>

app/views/dashboard/prompt_tasks/edit.html.erb
<div class="row align-items-center justify-content-between g-3 mb-3">
  <div class="col-12 col-md-auto">
    <h2 class="mb-0">Editing prompt task</h2>
  </div>
</div>

<%= render "form", prompt_task: @prompt_task, locals: { back_path: dashboard_prompt_task_path(@prompt_task) } %>

app/views/dashboard/prompt_tasks/index.html.erb
<div class="row align-items-center justify-content-between g-3 mb-3">
  <div class="col-12 col-md-auto">
    <h2 class="mb-0">Prompt tasks</h2>
  </div>
  <div class="col-12 col-md-auto d-flex">
    <%= link_to new_dashboard_prompt_task_path, class: "btn btn-outline-primary px-3 px-sm-5 me-2" do %>
      <span class="d-none d-sm-inline">
        New
      </span>
    <% end %>
  </div>
</div>

<% workers_stats = KeyValue.job_pool_workers_stats.json_value %>
<% if workers_stats["updated_at"] %>
  <p>
    Total workers: <%= workers_stats.fetch("total_workers_count", 0) %>
    Online workers: <%= workers_stats.fetch("online_workers_count", 0) %>
    Updated at: <%= time_tag Time.parse(workers_stats["updated_at"]) %>
  </p>
<% end %>

<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Prompt</th>
    <th scope="col">Status</th>
    <th scope="col">Preview</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @prompt_tasks.each do |task| %>
    <tr>
      <th scope="row">
        <%= task.id %>
      </th>
      <td>
        <%= task.prompt %>
      </td>
      <td>
        <%= task.status %>
      </td>
      <td>
        <%- if task.generated_image_url.present? %>
          <%= image_tag task.generated_image_url, size: "256x256" %>
        <% end %>
      </td>
      <td>
        <%= link_to "Show", dashboard_prompt_task_path(task) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @prompt_tasks %>

app/views/dashboard/prompt_tasks/new.html.erb
<div class="row align-items-center justify-content-between g-3 mb-3">
  <div class="col-12 col-md-auto">
    <h2 class="mb-0">New prompt task</h2>
  </div>
</div>

<%= render "form", prompt_task: @prompt_task %>

app/views/dashboard/prompt_tasks/show.html.erb
<div class="row align-items-center justify-content-between g-3 mb-3">
  <div class="col-12 col-md-auto">
    <h2 class="mb-0">Task #<%= @prompt_task.id %></h2>
  </div>
  <div class="col-12 col-md-auto d-flex">
    <%- if @prompt_task.pending? %>
      <%= button_to submit_dashboard_prompt_task_path(@prompt_task), method: :patch, class: "btn btn-primary px-3 px-sm-5 me-2" do %>
        <span class="d-none d-sm-inline">
          Run
        </span>
      <% end %>
      <%= link_to edit_dashboard_prompt_task_path(@prompt_task), class: "btn btn-outline-primary px-3 px-sm-5 me-2" do %>
        <span class="d-none d-sm-inline">
          Edit
        </span>
      <% end %>
    <% end -%>

    <div>
      <button class="btn px-3 btn-outline-secondary" type="button" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="true" data-bs-reference="parent">
        <i class="bi bi-three-dots"></i>
      </button>
      <ul class="dropdown-menu dropdown-menu-end" data-popper-placement="bottom-end">
        <li>
          <%= button_to "Delete", dashboard_prompt_task_path(@prompt_task), method: :delete, class: "dropdown-item text-danger" %>
        </li>
      </ul>
    </div>
  </div>
</div>

<dl class="row mb-3">
  <dt class="col-sm-3">
    Status
  </dt>
  <dd class="col-sm-9">
    <%= @prompt_task.status %>
  </dd>

  <%- unless @prompt_task.pending? %>
    <%- if @prompt_task.submitting_at.present? %>
      <dt class="col-sm-3">
        Submitting at
      </dt>
      <dd class="col-sm-9">
        <%= time_tag @prompt_task.submitting_at %>
      </dd>
    <% end -%>
    <%- if @prompt_task.submitted_at.present? %>
      <dt class="col-sm-3">
        Submitted at
      </dt>
      <dd class="col-sm-9">
        <%= time_tag @prompt_task.submitted_at %>
      </dd>
    <% end -%>
    <%- if @prompt_task.processing_at.present? %>
      <dt class="col-sm-3">
        Processing at
      </dt>
      <dd class="col-sm-9">
        <%= time_tag @prompt_task.processing_at %>
      </dd>
    <% end -%>
    <%- if @prompt_task.processed_at.present? %>
      <dt class="col-sm-3">
        Processed at
      </dt>
      <dd class="col-sm-9">
        <%= time_tag @prompt_task.processed_at %>
      </dd>
    <% end -%>
    <%- if @prompt_task.discarded_at.present? %>
      <dt class="col-sm-3">
        Discarded at
      </dt>
      <dd class="col-sm-9">
        <%= time_tag @prompt_task.discarded_at %>
      </dd>
    <% end -%>

    <%- if @prompt_task.generated_proof_url.present? %>
      <dt class="col-sm-3">
        Metadata
      </dt>
      <dd class="col-sm-9">
        <%= link_to @prompt_task.generated_proof_url, @prompt_task.generated_proof_url, target: "_blank" %>
      </dd>
    <% end %>
    <%- if @prompt_task.generated_image_url.present? %>
      <dt class="col-sm-3">
        Image
      </dt>
      <dd class="col-sm-9">
        <%= image_tag @prompt_task.generated_image_url %>
      </dd>
    <% end %>
  <% end -%>
</dl>

<hr />

<dl class="row mb-3">
  <dt class="col-sm-3">
    Prompt
  </dt>
  <dd class="col-sm-9">
    <%= @prompt_task.prompt %>
  </dd>

  <dt class="col-sm-3">
    Negative prompt
  </dt>
  <dd class="col-sm-9">
    <%= @prompt_task.negative_prompt %>
  </dd>

  <dt class="col-sm-3">
    SD model
  </dt>
  <dd class="col-sm-9">
    <%= @prompt_task.sd_model_name %>
  </dd>

  <dt class="col-sm-3">
    Sampler
  </dt>
  <dd class="col-sm-9">
    <%= @prompt_task.sampler_name %>
  </dd>

  <dt class="col-sm-3">
    Width x Height
  </dt>
  <dd class="col-sm-9">
    <%= @prompt_task.width %> x <%= @prompt_task.height %>
  </dd>

  <dt class="col-sm-3">
    Seed
  </dt>
  <dd class="col-sm-9">
    <%= @prompt_task.seed %>
  </dd>

  <dt class="col-sm-3">
    Steps
  </dt>
  <dd class="col-sm-9">
    <%= @prompt_task.steps %>
  </dd>

  <dt class="col-sm-3">
    CFG scale
  </dt>
  <dd class="col-sm-9">
    <%= @prompt_task.cfg_scale %>
  </dd>

  <dt class="col-sm-3">
    Clip skip
  </dt>
  <dd class="col-sm-9">
    <%= @prompt_task.clip_skip %>
  </dd>

  <%- if @prompt_task.hires_fix? %>
    <dt class="col-sm-3">
      Hires. upscaler
    </dt>
    <dd class="col-sm-9">
      <%= @prompt_task.hires_fix_upscaler_name %>
    </dd>

    <dt class="col-sm-3">
      Hires. upscale
    </dt>
    <dd class="col-sm-9">
      <%= @prompt_task.hires_fix_upscale %>
    </dd>

    <dt class="col-sm-3">
      Hires. steps
    </dt>
    <dd class="col-sm-9">
      <%= @prompt_task.hires_fix_steps %>
    </dd>

    <dt class="col-sm-3">
      Hires. denoising
    </dt>
    <dd class="col-sm-9">
      <%= @prompt_task.hires_fix_denoising %>
    </dd>
  <% end -%>
</dl>