config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :dashboard, path: "~" do
    root "home#index"

    resources :glossaries do
      scope module: "glossaries" do
        resources :vocabularies, only: %i[index create destroy] do
          collection do
            post "import"
          end
        end
      end
    end

    resources :meta_prompts do
      scope module: "meta_prompts" do
        resources :units, only: %i[index create update destroy]
      end
    end

    resources :prompt_tasks do
      collection do
        post "batch", action: "batch_create"
      end

      member do
        patch "submit"
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  get "/privacy", to: "home#privacy"
  get "/terms", to: "home#terms"

  get "401", to: "errors#unauthorized", as: :unauthorized
  get "403", to: "errors#forbidden", as: :forbidden
  get "404", to: "errors#not_found", as: :not_found

  devise_scope :user do
    namespace :users, as: "user" do
      resource :registration,
               only: %i[new create],
               path: "",
               path_names: { new: "sign_up" }

      resource :invitation, only: %i[] do
        get :edit, path: "accept", as: :accept
        get :destroy, path: "remove", as: :remove
      end

      match "sign_out" => "sessions#destroy", via: %i[get delete], as: :sign_out
    end
  end

  devise_for :users, skip: %i[registrations invitations], controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "sign_up", to: redirect("/users/sign_up")
  get "sign_in", to: redirect("/users/sign_in")

  namespace :account, module: "accounts" do
    resource :password, only: %i[show update]
    resource :profile, only: %i[show update]
  end
end

app/helpers/sidebar_helper.rb
# frozen_string_literal: true

module SidebarHelper
  def collapsed_sidebar?
    cookies["sidebar_collapsed"] == "true"
  end

  def use_sidebar(name = "application")
    @_sidebar_name = name
  end

  def has_sidebar?
    @_sidebar_name.present?
  end

  def render_sidebar
    return unless has_sidebar?
    render "layouts/sidebars/#{@_sidebar_name}"
  end
end

app/views/layouts/sidebars/_accounts.html.erb
<li class="links-group py-2">
  <strong class="d-flex w-100 align-items-center fw-semibold py-2">
    <%= t("layouts.sidebar.accounts.header") %>
  </strong>

  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <%= nav_link_to account_profile_path, controller: "accounts/profiles", class: "nav-link" do %>
        <%= t("layouts.sidebar.accounts.profile") %>
      <% end %>
    </li>
    <% if Devise.mappings[:user].database_authenticatable? %>
      <li class="nav-item">
        <%= nav_link_to account_password_path, controller: "accounts/passwords", class: "nav-link" do %>
          <%= t("layouts.sidebar.accounts.password") %>
        <% end %>
      </li>
    <% end %>
  </ul>
</li>

app/views/layouts/sidebars/_dashboard.html.erb
<li class="links-group py-2">
  <strong class="d-flex w-100 align-items-center fw-semibold py-2">
    <%= t("layouts.sidebar.dashboard.header") %>
  </strong>

  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <%= nav_link_to dashboard_root_path, controller: "dashboard/home", class: "nav-link" do %>
        <%= t("layouts.sidebar.dashboard.home") %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= nav_link_to dashboard_glossaries_path, paths: [{ controller: "dashboard/glossaries" }, { namespace: "dashboard/glossaries" }], class: "nav-link" do %>
        <%= t("layouts.sidebar.dashboard.glossaries") %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= nav_link_to dashboard_meta_prompts_path, paths: [{ controller: "dashboard/meta_prompts" }, { namespace: "dashboard/meta_prompts" }], class: "nav-link" do %>
        <%= t("layouts.sidebar.dashboard.meta_prompts") %>
      <% end %>
    </li>
    <li class="nav-item">
      <%= nav_link_to dashboard_prompt_tasks_path, controller: "dashboard/prompt_tasks", class: "nav-link" do %>
        <%= t("layouts.sidebar.dashboard.prompt_tasks") %>
      <% end %>
    </li>
  </ul>
</li>